# The URL the site will be built for
base_url = "https://www.jntrnr.com"
theme = "simple-dev-blog"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feed = true

taxonomies = [{ name = "tags" }]

[extra]
# Put all your custom variables here
nav = [
  { name = "Home", path = "/" },
  { name = "Tags", path = "/tags" },
  { name = "Twitter", path = "https://www.twitter.com/jntrnr" },
  { name = "Mastodon", path = "https://mastodon.social/@jntrnr" },
  { name = "Atom/RSS", path = "/atom.xml" },
  { name = "Poems", path = "/poems/waitingtogrow" },
]

latest_text = "Check out my latest post:"

icon = "icon.png"
profile_large = "profile.jpg"
profile_small = "icon.png"

accent = "#05a081"
accent_light = "#82d0c0"

author = "JT"

footer_about = """
A simple dev-blog theme created by Bennett. You can follow him on [Github](https://github.com/bennetthardwick) (if you like).
"""

not_found_message = """
This is not the page you're looking for... return back to [safety?](/)
"""
